services:
  backend:
    image: ghcr.io/lucasgwbr/registroreceita/backend:latest
    build:
      context: ./backend

  frontend:
    image: ghcr.io/lucasgwbr/registroreceita/frontend:latest
    build:
      context: ./frontend