spring.application.name=RegistroReceita
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=SENHA_DE_APP_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=Y3I0Z1J4T3VzY1VwMzlhSjdoNGV3Wk5mN0o2cEszcjFyMmM5eTRQeTZzN0p0NHZ5R1U=
