name: Java CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4

      - name: Instalar o Java 21 no servidor
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build, Testes e Análise do SonarQube
        working-directory: ./backend
        run: mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}