name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Pegar o código do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar o Java 21 no servidor
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build, Testes e Análise do SonarQube
        working-directory: ./backend
        run: mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Login no ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push — backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/lucasgwbr/registroreceita/backend:latest

      - name: Build e Push — frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/lucasgwbr/registroreceita/frontend:latest
      - name: Deploy automático em homolog (SSH Nativo com Debug)
        env:
          SSH_KEY: ${{ secrets.VM_SSH_KEY }}
          HOST: ${{ secrets.VM_HOST }}
          USER: ${{ secrets.VM_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Adicionamos -v (verbose) e desativamos a checagem estrita para forçar a conexão
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 "$USER@$HOST" << 'EOF'
            # Ativa a exibição dos comandos que estão rodando na VM
            set -x 
          
            cd ~/app
            docker compose -f docker-compose.yml -f docker-compose.homolog.yml --env-file .env.homolog pull
            docker compose -f docker-compose.yml -f docker-compose.homolog.yml --env-file .env.homolog up -d --remove-orphans
            docker image prune -f
            echo "✅ Homolog atualizado com sucesso!"
          EOF